### PR TITLE
Indexer can time out waiting for a Mint response if using the CTServer.

### PR DESCRIPTION
**Pull request by AndrewGorton**

### CODE REVIEW

**Comment by philandstuff** [comment]
what does "to reduce SOCKET_READ_TIMEOUT" mean? Are you reducing the timeout threshold value by reducing the batch size? Or were you seeing too many timeouts and found that reducing the batch size reduced that?

The higher batch size was introduced in order to facilitate loading large data sets (such as addresses).  Reducing it so far will adversely affect performance when loading large data sets.

**Comment by AndrewGorton** [comment]
Mint takes a batched up (\n-delimited list) of objects to be minted. These are sent one at a time to the CTServer. It takes a few seconds for the CTServer to respond each time, so the Loader can time out waiting for a response when loading batches of 2000 records.

**Comment by philandstuff** [comment]
@AndrewGorton oh I see, that's really useful context. Could you amend your commit message to include this information? This would be really helpful if someone (eg me) comes along later and wonders why the BATCH_SIZE has the value that it has.

**Comment by om-sharma** [comment]
Should we optionally provide batch size from load command?

**Comment by philandstuff** [comment]
@om-sharma if there's a need for that, then yes. But that's probably a separate PR?

**Pull request merged**
